runtime: nodejs18
env: standard

instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
  target_throughput_utilization: 0.6
  max_concurrent_requests: 80

env_variables:
  FRONTEND_URL: "https://gmdozer.vercel.app"
  PORT: "8081"
  NODE_ENV: "production"

handlers:
  - url: /socket.io/.*
    script: auto
    secure: always
    http_headers:
      Access-Control-Allow-Origin: "*"
      Access-Control-Allow-Methods: "GET, POST, OPTIONS"
      Access-Control-Allow-Headers: "Content-Type, Authorization"
      Access-Control-Allow-Credentials: "true"

  - url: /.*
    script: auto
    secure: always

vpc_access_connector:
  name: "projects/gmdozer/locations/asia-east1/connectors/gmdozervpc"

network:
  session_affinity: true
  forwarded_ports:
    - 8081